In [1]:
#1Create Two numpy array of size 4 X 5 and 5 X 4.
import numpy as np
import random as rand

arra1=np.array(np.arange(0,20).reshape(5,4))
arra2=np.array(np.arange(0,20).reshape(4,5))
arra1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [2]:
arra2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [3]:
#2.Randomly Initalize that array
array=np.random.randint(1, 100, size=(4, 5))
array

array([[61, 90, 14, 10, 83],
       [86, 38,  2, 24,  4],
       [45, 40, 79, 38, 22],
       [43, 86, 76, 29, 25]])

In [4]:
#3.Perform matrix multiplication
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
print(np.dot(x, y))
print(np.dot(arra1,arra2))

[[19 22]
 [43 50]]
[[ 70  76  82  88  94]
 [190 212 234 256 278]
 [310 348 386 424 462]
 [430 484 538 592 646]
 [550 620 690 760 830]]


In [5]:
#4.4) Perform elementwise matrix multiplication
print(np.multiply(arra1,arra1))

[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]
 [144 169 196 225]
 [256 289 324 361]]


In [6]:
#5.Find mean, median of the first matrix.
np.mean(arra1)

9.5

In [7]:
np.mean(arra1,axis=0)
np.mean(arra1,axis=1)
np.median(arra1)

np.median(arra1,axis=0)
np.median(arra1,axis=1)

array([ 1.5,  5.5,  9.5, 13.5, 17.5])

In [10]:
#6.Get the transpose of that Matrix that you created. Create a square matrix and find its deter-
#minant.
print(arra1.T)
# square matrix 3*3
array3=np.array([[1,2,3],[4,5,6],[7,8,9]])
array3
np.linalg.det(array3)

[[ 0  4  8 12 16]
 [ 1  5  9 13 17]
 [ 2  6 10 14 18]
 [ 3  7 11 15 19]]


0.0

In [16]:
#Obtain each row in the second column of the first array.
array3[:,1]


array([2, 5, 8])

In [15]:
nparrayCentered = arra1.T - np.mean(arra1, axis=1) 
# Remove the mean for␣
##,→each row
nparrayCentered = nparrayCentered.T #
nparrayCentered

array([[-1.5, -0.5,  0.5,  1.5],
       [-1.5, -0.5,  0.5,  1.5],
       [-1.5, -0.5,  0.5,  1.5],
       [-1.5, -0.5,  0.5,  1.5],
       [-1.5, -0.5,  0.5,  1.5]])